INSERT INTO public.inventario_items (categoria, valor, orden) VALUES
  ('productos', 'AGUACATE', 0),
  ('productos', 'AGUACATE BIO', 1),
  ('productos', 'MANGO BIO', 2),
  ('productos', 'MANGO PREMIUM', 3),
  ('productos', 'MANGO ESTÁNDAR', 4),
  ('productos', 'PIÑA', 5),
  ('productos', 'MANGO HIDRO', 6),
  ('productos', 'PIÑA BIO', 7),
  ('trabajos', 'REVISIÓN', 0),
  ('trabajos', 'CONFECCIÓN', 1),
  ('trabajos', 'CALIBRAR', 2),
  ('trabajos', 'TIRAR', 3),
  ('trabajos', 'REPALETIZAR', 4),
  ('trabajos', 'RECONFECCIÓN', 5),
  ('tiposReconfeccion', 'Repaletizado', 0),
  ('tiposReconfeccion', 'Cambio Caja', 1),
  ('tiposReconfeccion', 'Etiquetado', 2),
  ('tiposReconfeccion', 'Correcalibre', 3),
  ('subtareas', 'ETIQUETAR', 0),
  ('subtareas', 'CAMBIAR CAJA', 1),
  ('subtareas', 'QUITAR CORONA', 2),
  ('subtareas', 'CAMBIAR CAJA + CORBATA', 3),
  ('subtareas', 'PONER CORBATA', 4),
  ('subtareas', 'CORRECALIBRE + CAMBIO CAJA', 5),
  ('subtareas', 'CORRECALIBRE', 6),
  ('cajas', 'MADERA AGUACATE', 0),
  ('cajas', 'MADERA PIÑA', 1),
  ('cajas', 'MANGO 2Kg', 2),
  ('cajas', '40x26x10,5', 3),
  ('cajas', '40x30x8', 4),
  ('cajas', 'AGUACATE 40x30x9,5', 5),
  ('cajas', '40x30x14', 6),
  ('cajas', 'FRUNET 40x30x14', 7),
  ('cajas', '60x40x9,5', 8),
  ('cajas', '60x40x12', 9),
  ('cajas', '60x40x14', 10),
  ('cajas', 'PIÑA FRUNET', 11),
  ('cajas', 'PETIT 2Kg', 12),
  ('cajas', 'PIÑA TROPICAL', 13),
  ('cajas', 'PIÑA GENERICA', 14),
  ('cajas', 'FRUNET ABIERTA', 15),
  ('cajas', 'PIÑA TROPICAL NEGRA', 16),
  ('cajas', 'TAPA FONDO FRUNET GRANDE', 17),
  ('cajas', 'TAPA FONDO FRUNET PEQUEÑA', 18),
  ('cajas', 'MANGO ORIGEN', 19),
  ('cajas', 'DRAGON 40x30x9,5', 20),
  ('cajas', 'DRAGON 40x30x13', 21),
  ('cajas', 'LL4310', 22),
  ('cajas', 'EPS104', 23),
  ('cajas', 'EPS154 RAMA', 24),
  ('cajas', 'EPS154', 25),
  ('cajas', 'BLANCA IMPORTACION', 26),
  ('cajas', 'LOGIFRUIT 612', 27),
  ('cajas', 'BLL4310', 28),
  ('cajas', 'CALIBRADO 4KG-6KG', 29),
  ('cajas', 'CALIBRADO 2KG-4KG-6KG', 30),
  ('cajas', 'CALIBRADO 2KG-4KG-6KG-10KG', 31),
  ('cajas', 'CALIBRADO 2KG-4KG', 32),
  ('cajas', 'CALIBRADO 2Kg', 33),
  ('cajas', 'CALIBRADO 4Kg-6Kg-10Kg', 34),
  ('cajas', 'CALIBRADO 4Kg-10Kg', 35),
  ('cajas', 'PIÑA VERTICAL', 36),
  ('envases', 'TARRINA', 0),
  ('envases', 'BOLSA', 1),
  ('envases', 'MAYA', 2),
  ('envases', 'NO', 3),
  ('envases', 'SOBRE PAPEL MANGO', 4),
  ('envases', 'CORBATA', 5),
  ('etiquetas', 'SI', 0),
  ('etiquetas', 'NO', 1),
  ('etiquetas', 'ETIQ CAJA', 2),
  ('otros', 'ALVEOLO CARTON', 0),
  ('otros', 'ALVEOLO PAPEL', 1),
  ('otros', 'TAPA', 2),
  ('otros', 'SEPARADOR', 3),
  ('clientes', 'ABC FRESH B.V.', 0),
  ('clientes', 'AGRAL (FITIMEX)', 1),
  ('clientes', 'AGRI-COMMERCE SA', 2),
  ('clientes', 'AGROMART BALEAR S.L.', 3),
  ('clientes', 'AGROPONS S.L.', 4),
  ('clientes', 'AGROSOL PERU EXPORT & CIA S.A.C.', 5),
  ('clientes', 'AGRUPA ALMAYATE S.L', 6),
  ('clientes', 'AKRO TRADE', 7),
  ('clientes', 'ALPA ALIMENTOS FRESCOS S.L.U.', 8),
  ('clientes', 'AXARFRUIT S.L.', 9),
  ('clientes', 'AZEFRESH B.V.', 10),
  ('clientes', 'BADIA HORTOFRUIT S.L.', 11),
  ('clientes', 'BAUZA S.A.S', 12),
  ('clientes', 'BIENEK FRUCHTHANDEL GMBH', 13),
  ('clientes', 'BIO ALGARROBO S.L.', 14),
  ('clientes', 'BIO LANZAC S.L.', 15),
  ('clientes', 'BIOALCORES S.L.', 16),
  ('clientes', 'BLAMPIN IMPORT-ZONE SUD', 17),
  ('clientes', 'BLAS EL CANARIO S.L.U (CENTRAFRUIT)', 18),
  ('clientes', 'CANOVA PRODUCTOS BIOLOGICOS, S.L.', 19),
  ('clientes', 'CERISE ET POTIRON - PROVIDIS LOGISTIQUE', 20),
  ('clientes', 'CORTIJO CUEVAS S.L.', 21),
  ('clientes', 'CROWDFARMING SL', 22),
  ('clientes', 'CRUCHAUDET GRANDJEAN', 23),
  ('clientes', 'DAGAB INKÖP (AXFOOD)', 24),
  ('clientes', 'DESMETTRE RUNGIS', 25),
  ('clientes', 'ENVAPAL TRADE S.L.', 26),
  ('clientes', 'ERWIN DEHMEL INH. ROLF DEHMEL', 27),
  ('clientes', 'EUROBANAN GALICIA S.L', 28),
  ('clientes', 'EXOFI FRESH MARKET SPRL', 29),
  ('clientes', 'FAIRFRUIT GMBH', 30),
  ('clientes', 'FITIMEX S.P.A.', 31),
  ('clientes', 'FRESH ANANAS EXPORT LIMITADA', 32),
  ('clientes', 'FRESH SOLUTIONS NETHERLANDS (MANGO)', 33),
  ('clientes', 'FRUITS CMR', 34),
  ('clientes', 'FRUTARIA MARKETS ZARAGOZA S.L.', 35),
  ('clientes', 'FRUTAS CARPIO', 36),
  ('clientes', 'FRUTAS EL CASTILLO C.B.', 37),
  ('clientes', 'FRUTAS RUBIO SANCHEZ E HIJOS, S.L', 38),
  ('clientes', 'FRUTURA (SPAR)', 39),
  ('clientes', 'GAMINAFRUITS', 40),
  ('clientes', 'GEORGES HELFER SA', 41),
  ('clientes', 'GIOVANELLI FRUCHTIMPORT AG', 42),
  ('clientes', 'GST PRIMEVER (PRIMEVER ILE DE FRANCE SAS)', 43),
  ('clientes', 'GYÜMÖLCSÉRT KFT. (FAIR FRUIT)', 44),
  ('clientes', 'HEICS SILKWAY', 45),
  ('clientes', 'HOOFDMAN-ROODZANT B.V.', 46),
  ('clientes', 'HORTIFRUT H.V. MOLINA S.L.', 47),
  ('clientes', 'ICA SVERIGE AB', 48),
  ('clientes', 'IPER MONTEBELLO S.P.A.', 49),
  ('clientes', 'ISLA BUENA UNIPESSOAL LDA', 50),
  ('clientes', 'JACQUES REMY & FILS', 51),
  ('clientes', 'JMF PARTENARIAT', 52),
  ('clientes', 'JOSE LUIS MONTOSA S.L.', 53),
  ('clientes', 'JSC VKUSVILL', 54),
  ('clientes', 'KEELINGS', 55),
  ('clientes', 'KELLER FRESH & Co Gmbh', 56),
  ('clientes', 'LA RONDEÑA FRUIT', 57),
  ('clientes', 'LACOUR EXOTIC INTERNATIONAL', 58),
  ('clientes', 'LE JARDIN DE POMEYROL SAS', 59),
  ('clientes', 'MANAGU FRUTAS TROPICALES', 60),
  ('clientes', 'MERCADONA S.A.', 61),
  ('clientes', 'MIÑANA SANGERMAN S.A.U', 62),
  ('clientes', 'NATURAL TROPIC, S.L.', 63),
  ('clientes', 'NATURKOST SCHRAMM IMPORT-EXPORT GMBH', 64),
  ('clientes', 'NUFRI, S.L.U.', 65),
  ('clientes', 'OLYMPIC FRUIT', 66),
  ('clientes', 'PARIS HERBES', 67),
  ('clientes', 'PETER KEUTHMANN GMBH&CO. KG', 68),
  ('clientes', 'PRIMI EXOTIC FRUIT SRL', 69),
  ('clientes', 'PRODUCTOS ECOLÓGICOS BIOTROPIC S.L.', 70),
  ('clientes', 'PROVENCE VIVARAIS SAS', 71),
  ('clientes', 'PRZEDSIEBIORSTWO WALFRED S.C. WALDEMAR CWIEK ALFRED CWIEK', 72),
  ('clientes', 'RECISUR MALAGA S..L.', 73),
  ('clientes', 'RICO TOME Y PATRICIA PILAR', 74),
  ('clientes', 'RIMI LATVIA SIA', 75),
  ('clientes', 'S.A.S. ALROPRIM BLASCO', 76),
  ('clientes', 'SAS PRIM SELECT', 77),
  ('clientes', 'SCAFEL.LECLERC', 78),
  ('clientes', 'SMITH & BROCK S.A.S', 79),
  ('clientes', 'TF INTERNATIONALl BV', 80),
  ('clientes', 'TROPICAL MILLENIUM S.L.', 81),
  ('clientes', 'VASAKI IBERICA SL', 82),
  ('clientes', 'WESTFALIA FRUIT FRANCE', 83),
  ('clientes', 'ZUENDORF & ZERRES GmbH', 84),
  ('proveedores', 'ACUIFERO CASMA  SA', 0),
  ('proveedores', 'AGROSOL PERU EXPORT & CIA S.A.C.', 1),
  ('proveedores', 'ALMAGRO NATURE S.L.U.', 2),
  ('proveedores', 'ANTONIO MANUEL MARTÍN GONZÁLEZ', 3),
  ('proveedores', 'BAEZA LARA, BELINDA MARIA', 4),
  ('proveedores', 'BIO ALGARROBO S.L.', 5),
  ('proveedores', 'CASI SCA', 6),
  ('proveedores', 'CORTIJO CUEVAS S.L.', 7),
  ('proveedores', 'DEL MONTE FRESH PRODUCE SAU', 8),
  ('proveedores', 'ECOINVER BIO S.L.', 9),
  ('proveedores', 'EXOTIC S PRODUCERS & PACKERS S.A.C.', 10),
  ('proveedores', 'FRESH ANANAS EXPORT LIMITADA', 11),
  ('proveedores', 'FRUGALP AGRÍCOLA EXPORTADORA G-P CÍA.LTD', 12),
  ('proveedores', 'FRUNET S.L.', 13),
  ('proveedores', 'FRUTAS ALHAMBRA', 14),
  ('proveedores', 'FYFFES INTERNATIONAL', 15),
  ('proveedores', 'GONZALEZ GONZALEZ, MERCEDES', 16),
  ('proveedores', 'JALHUCA EXPLOTACIONES S.L.', 17),
  ('proveedores', 'JOSE SANCHEZ CAMACHO', 18),
  ('proveedores', 'KEELINGS FRESH INTERNATIONAL LIMITED', 19),
  ('proveedores', 'KRAAIJEVELD GROENTE EN FRUIT B.V.', 20),
  ('proveedores', 'LOMA MECIAS C.B.', 21),
  ('proveedores', 'MARTIN  RUIZ, IGNACIO', 22),
  ('proveedores', 'MARTÍN RUIZ , FRANCISCO ANTONIO', 23),
  ('proveedores', 'MJ AGROASESORES S.L.', 24),
  ('proveedores', 'MOLINA  MARTIN, MARIA BELEN', 25),
  ('proveedores', 'NATURAL SWEETIES TROPICAL LAND SRL', 26),
  ('proveedores', 'NUFRI, S.L.U.', 27),
  ('proveedores', 'PINABAN EXPORT INC-ACON', 28),
  ('proveedores', 'PRIMA FRUTA AGRICOLA S.A.C.', 29),
  ('proveedores', 'S.A.T. LAS HORTICHUELAS', 30),
  ('proveedores', 'SANCHEZ MOLINA , ALEJANDRO', 31),
  ('proveedores', 'SCHRIJVERSHOF B.V.', 32),
  ('proveedores', 'SERRA ORGANIC S.A.', 33),
  ('proveedores', 'SOLARWIND FRUITS', 34),
  ('proveedores', 'SOLEIL D''AFRIQUE', 35),
  ('proveedores', 'SUREXPORT LEVANTE S.L.U.', 36),
  ('proveedores', 'SWEET FRUITS S.A.', 37),
  ('proveedores', 'UNICA GROUP, S.C.A (VENTA)', 38),
  ('proveedores', 'VALLE SAN MIGUEL S.A.C.', 39);
